### ISSUE TITLE
Raspberry pi 4 model B support

### ISSUE THREAD

**Issue by TaiJuWu** [apache/nuttx#11586]
Can Nuttx support raspberry 4 model B?
Or anyone work on this board?

**Comment by alandeassis** [comment]
@TaiJuWu the initial support to Raspberry Pi board (the first board) was removed by Greg some years ago because nobody was interested to still working in the port: https://bitbucket.org/patacongo/obsoleted/src/master/Patches/Remove-arch-bcm2708-2019-01-02.patch

If you want to work on it, you can look that initial support and use it as reference.

**Comment by TaiJuWu** [comment]
> @TaiJuWu the initial support to Raspberry Pi board (the first board) was removed by Greg some years ago because nobody was interested to still working in the port: https://bitbucket.org/patacongo/obsoleted/src/master/Patches/Remove-arch-bcm2708-2019-01-02.patch
> 
> If you want to work on it, you can look that initial support and use it as reference.

Thanks for your information.

**Comment by linguini1** [comment]
Checking if this is in development at all? I am interested in contributing to get support for this board.

**Comment by TaiJuWu** [comment]
> Checking if this is in development at all? I am interested in contributing to get support for this board.

No, I am not working on it.

**Comment by linguini1** [comment]
Could this issue be assigned to me? I have begun work on it.

**Comment by xiaoxiang781216** [comment]
> Could this issue be assigned to me? I have begun work on it.

Done, thanks.

**Comment by linguini1** [comment]
So I have an initial implementation for this board (the 4GB variant is all I have access to for testing right now) which boots successfully and has NSH running with a UART console. It passes the `ostest` as well.

Obviously I plan to implement some drivers for the board so it can actually be used for programming/development (I2C, remaining UARTs, GPIO, etc.). I am wondering, however, at what point is a port to a new board considered "good enough" to be merged? I imagine that full support for everything on the board (like HDMI ports, Bluetooth, etc.) does not have to be implemented to be merged, but is there a guideline on how complete it must be at a minimum to become part of the main source tree?

I ask only because I think that at some point in the development process I'd like to be able to call it "complete enough" to allow for it to be merged and more accessible to others to make changes/add features.

**Comment by xiaoxiang781216** [comment]
it's enough to implement uart and timer driver to ensure the port enter nsh correctly.

**Comment by csukuangfj** [comment]
Any progress on this issue?

**Comment by linguini1** [comment]
> Any progress on this issue?

@csukuangfj I have managed to get NuttX booting into NSH on the 4GB RAM model, haven't been able to test on other models. I have a partially made I2C driver which is quite buggy and is only able to do read operations on the bus. I was starting on SPI aand got quite busy with my coursework. What I'll likely do is open a PR with what I've got working so far and mark features as incomplete on the board docs. Then hopefully the community can pitch in and we can get more features done quicker!
