### ISSUE TITLE
usbtrace causes crash

### ISSUE THREAD

**Issue by Virus-V** [apache/nuttx#12181]
When I was debugging the STM32F405 USB function, I encountered a crash.

<img width="1097" alt="image" src="https://github.com/apache/nuttx/assets/32447708/8e3634fb-54e8-40ca-aee7-b15432e02e2d">

It seemed that the data structure was damaged.

The cause of this problem is that the **interrupt was responded to in the critical section**.

This problem only occurred after I turned on the USB DEBUG function. 

<img width="659" alt="image" src="https://github.com/apache/nuttx/assets/32447708/0e7463ac-dbef-4be8-956a-6fd1f5f47043">

I found that in the `syslog_putc` function, different output functions are called according to the current calling context.

<img width="834" alt="image" src="https://github.com/apache/nuttx/assets/32447708/b668a2c5-0fd1-47f9-9a26-310e744671f0">

However, it does not handle the current situation in the critical section, resulting in task scheduling and interrupts being turned on in the critical section.

**Comment by acassis** [comment]
@Virus-V nice work finding and debugging this issue! Kudos!!!

@xiaoxiang781216 @raiden00pl any suggestion?

@Virus-V maybe using RAMLOG as SYSLOG instead of SYSLOG over serial could help, them you just run dmesg later to see what happened.

Note: take care with using USB Trace, as Greg explained some years ago: when you add tracing you are changing the timing of USB and it could introduce issues.

**Comment by xiaoxiang781216** [comment]
This is a known issue we found many time before: https://github.com/apache/nuttx/issues/1138
One possible solution postpone the preemption until leave_critical_section.

**Comment by Virus-V** [comment]
It is unsafe to call syslog in a critical section.

Not only usbdev, there are similar codes in other drivers in nuttx (such as drivers/timers/pwm.c).

**Comment by xiaoxiang781216** [comment]
let's close this issue and focus on #1138
