### ISSUE TITLE
Littlefs not compatible with non-C99 bool

### ISSUE THREAD

**Issue by thebolt** [apache/nuttx#9032]
We have discovered an interesting interaction between Littlefs and NuttX compiled without C99 bool support.

The short story is that Littlefs assumes C99 compiler, and that conversions to "bool" follows C99 _Bool conversion rules (that is, any non-zero integer independent of size evaluates to true) however when compiled together with Nuttx without CONFIG_C99_BOOL8=y set, bool will be uint8_t and truncation will happen, causing bugs in littelfs code (basically the code does bool x = y & 0xF000 where y is a uint16_t) .

My colleague have tried to submit a fix to Littlefs ( https://github.com/littlefs-project/littlefs/pull/772 ) , however as they assume C99 the fix will not be merged there. A suggested fix in nuttx to at least avoid the problem would be to make littlefs build depend on CONFIG_C99_BOOL8. Or does anyone have a better suggestion how to fix or reduce the risk of hitting the actual issue?

**Comment by xiaoxiang781216** [comment]
it make sense to let littlefs depends on C99_BOOL8, if the littlefs community doesn't accept the patch

**Comment by pkarashchenko** [comment]
Since C99 is "mandatory" for littlefs so why not to add compiler flag in the corresponding Makefile?

**Comment by geky** [comment]
I'm curious what the consequence of requiring CONFIG_C99_BOOL8=y is.

littlefs depends on a number of c99 features, so, as far as I'm aware, it simply won't compile with a c89 compiler due to missing language features. But if you have a c99 you should have `_Bool`.

Is this the result of historic compatibility issues?

**Comment by xiaoxiang781216** [comment]
> I'm curious what the consequence of requiring CONFIG_C99_BOOL8=y is.
> 
> littlefs depends on a number of c99 features, so, as far as I'm aware, it simply won't compile with a c89 compiler due to missing language features.

Yes, gcc/clang should enable all c99 feature by default, that's why littlefs pass the build without error.

> But if you have a c99 you should have `_Bool`.
> 
> Is this the result of historic compatibility issues?

Look like the code detect whether compiler support _Bool doesn't work as expect:
https://github.com/apache/nuttx/blob/master/include/nuttx/compiler.h#L56-L62
https://github.com/apache/nuttx/blob/master/include/stdbool.h#L61-L81

**Comment by xiaoxiang781216** [comment]
@thebolt can you try where https://github.com/apache/nuttx/pull/6210 could fix your issue?

**Comment by XinStellaris** [comment]
I have tried current code.  The result shows if CONFIG_C99_BOOL is supported, then following type cast is good:

**Comment by thebolt** [comment]
I realize now that I should have included that we are a few versions behind on Nuttx (as often is the case in bigger products with stability requirements), and should have checked if the code in stdbool.h (and associated headers) had changed since.. 

Well then, as it seems latest Nuttx handles it OK, then we will run with a local defconfig that has CONFIG_C99_BOOL8 set for now, and then it will solve itself once we bump our version. Guess we can close this issue
