### ISSUE TITLE
Connecting to local socket blocks forever after PR #8985

### ISSUE THREAD

**Issue by pussuw** [apache/nuttx#9241]
It seems like there is a regression with sockets after PR #8985  . At least local sockets are affected, did not test others.

Connecting to local socket blocks forever into pipecommon_open : ret = nxsem_wait(&dev->d_wrsem);

It happens via call to local_tx_open, which opens the local write-only FIFO.
```
static int local_tx_open(FAR struct local_conn_s *conn, FAR const char *path,
                         bool nonblock)
{
  int oflags = nonblock ? O_WRONLY | O_NONBLOCK : O_WRONLY;
  int ret;

  ret = file_open(&conn->lc_outfile, path, oflags);
```

If I force nonblock to true, everything works as before. I'm not sure how to fix this properly so this is why I brought this up. I think there is straight up a logic error there, I don't think allocating FIFOs for sockets should block, ever.

If someone tells me how it SHOULD work I'll happily fix it.

NOTE: The socket is a blocking socket, but what I want is that connect() blocks until someone accept():s it. However, due to the regression the client side code does not reach the point where accept is handled, and where it SHOULD block for real until the server accepts. 

I mention this because I thought of patching the application by temporarily setting O_NONBLOCK before calling connect() and clearing it after connect(). But that would mean not blocking until accept() is dispatched as well, which is not what I want...

**Comment by tmedicci** [comment]
Hi @pussuw , thanks for reporting...

> It seems like there is a regression with sockets after PR https://github.com/apache/nuttx/pull/8985 . At least local sockets are affected, did not test others.

It seems it affects only local sockets because it uses a FIFO to exchange data. BTW, it can be checked using `sim:ustream`:

```
nsh> server &
server [4:100]
nsh> server: Accepting connections on /dev/fifo ...

nsh> client 
client: Connecting to /dev/fifo...
```
> I'm not sure how to fix this properly so this is why I brought this up. I think there is straight up a logic error there, I don't think allocating FIFOs for sockets should block, ever.

I couldn't figure out how to fix this yet (and, also, I'm not that familiar with the local sockets). But the problem itself can be described as:

- [`local_accept`](https://github.com/apache/incubator-nuttx/blob/75ecbd4382d57580af251bb55e45b7ef207564b7/net/local/local_accept.c#L98) (the server side): doesn't try to open the FIFO if there are no waiters (that is, some client trying to connect). It keeps waiting for `local_waitlisten`, which is a semaphore, basically.
- [`local_open_client_tx`](https://github.com/apache/incubator-nuttx/blob/82e2e4124a3485f827926298d35e703027d16e13/net/local/local_connect.c#L109) blocks trying to open the FIFO.
- [`local_waitlisten`](https://github.com/apache/incubator-nuttx/blob/75ecbd4382d57580af251bb55e45b7ef207564b7/net/local/local_accept.c#L48) only returns after `local_open_client_tx` returns (and it won't return if no server-sided FIFO opens), specifically [here](https://github.com/apache/incubator-nuttx/blob/82e2e4124a3485f827926298d35e703027d16e13/net/local/local_connect.c#L132).

> If someone tells me how it SHOULD work I'll happily fix it.

I'd say, preliminary, that this new behavior of FIFO possibly changes the logic of waiting at `local_waitlisten` or opening the client side after notifying the server that it also can open the server side of that same FIFO. 

I accept more ideas on how to handle it properly ;)

**Comment by pussuw** [comment]
Hi @tmedicci and thanks for the answer. Yes I debugged the root cause and like you said, the problem is local_open_client_tx. The "nonblocking"-flag is propagated to this function but I'm not sure if opening the FIFO should block ever.

IMO the client should block ONLY if the server is not there to accept the connection, blocking/waiting until someone accepts the connection. Creating the FIFO is just the transport for the local socket, there is no need to wait for readers/writers like with pipes.

However, as I said I'm not too familiar with local sockets either (besides using them extensively) so cannot say for sure that this is the case.

**Comment by tmedicci** [comment]
Hi @pussuw .

Probably, the blocking feature of the FIFO would be able to handle upcoming connections. However, in order to restore the intended functionality, I went the easy way in https://github.com/apache/nuttx/pull/9244. 

Could you please evaluate it?

**Comment by pussuw** [comment]
Yes, I think #9244 sufficiently fixes the regression. Thanks!
